# Generated by Django 5.2.13 on 2026-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='⚙️', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('tags', models.CharField(help_text='Tags separados por comas', max_length=300)),
                ('color', models.CharField(default='#00e5ff', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
