# Generated by Django 5.2.13 on 2026-04-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='⚙️', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('tags', models.CharField(help_text='Tags separados por comas', max_length=300)),
                ('color', models.CharField(default='#00e5ff', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('servicio_interes', models.CharField(blank=True, default='', max_length=120)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de contacto',
                'verbose_name_plural': 'Solicitudes de contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
